// <auto-generated />
namespace Vidly001.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewValidationMovieNameRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewValidationMovieNameRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201806261328238_NewValidationMovieNameRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
